version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install buildstock
          command: |
            conda install -c conda-forge -y -q scipy numpy pandas "pyarrow>=0.14.1" dask joblib pyyaml
            pip install .[dev] --progress-bar off
      - run:
          name: Run PyTest
          command: |
            pytest -v
      - run:
          name: Run coverage tests
          when: always
          command: |
            set +e
            coverage run --source=buildstockbatch -m pytest > /dev/null 2>&1
            coverage report -m
            coverage html -d /tmp/coverage_report
      - run:
          name: Run style checks
          when: always
          command: |
            flake8 buildstockbatch
      - store_artifacts:
          path: /tmp/coverage_report
          destination: coverage-report
      - run:
          name: Build documentation
          when: always
          command: |
            apt-get install make
            cd docs
            make html
            mkdir /tmp/docs
            cp -r _build/html/* /tmp/docs
      - persist_to_workspace:
          root: /tmp
          paths:
            - docs
      - store_artifacts:
          path: /tmp/docs
          destination: docs
  docs-deploy:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: 
          name: Disable jekyll builds
          command: touch /tmp/docs/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages
            git config user.email "noel.merket@nrel.gov"
            git config user.name "Noel Merket CI Bot"
      - add_ssh_keys:
          fingerprints:
            - "78:38:f3:2e:94:a6:20:46:3e:40:ee:31:3d:1e:95:09"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] update api docs" --dist /tmp/docs

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master

