name: BuildStockBatch Tests
on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: ['3.8', '3.9', '3.10', '3.11']
        python-version: ['3.11']
    name: Tests - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: buildstockbatch
      - uses: actions/checkout@v3
        with:
          repository: NREL/resstock
          path: resstock
          ref: develop
      - uses: actions/checkout@v3
        with:
          repository: NREL/comstock-internal
          path: comstock
          ref: bsb-integration-tests
          ssh-key: ${{ secrets.COMSTOCK_SSH_KEY }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Download weather
        run: |
          mkdir weather
          cd weather
          wget --quiet https://data.nrel.gov/system/files/156/BuildStock_TMY3_FIPS.zip
      - name: Download and Extract OpenStudio 3.6.1
        run: |
          wget -q https://github.com/NREL/OpenStudio/releases/download/v3.6.1/OpenStudio-3.6.1+bb9481519e-Ubuntu-20.04-x86_64.tar.gz
          tar xzf OpenStudio-3.6.1+bb9481519e-Ubuntu-20.04-x86_64.tar.gz
          rm OpenStudio-3.6.1+bb9481519e-Ubuntu-20.04-x86_64.tar.gz
      - name: Download and Extract OpenStudio 3.4.0 for ComStock Tests
        run: |
          wget -q https://github.com/NREL/OpenStudio/releases/download/v3.4.0/OpenStudio-3.4.0+4bd816f785-Ubuntu-20.04.tar.gz
          tar xzf OpenStudio-3.4.0+4bd816f785-Ubuntu-20.04.tar.gz
          rm OpenStudio-3.4.0+4bd816f785-Ubuntu-20.04.tar.gz
      - name: Install buildstockbatch
        run: |
          cd buildstockbatch
          python -m pip install --progress-bar off --upgrade pip
          pip install .[dev] --progress-bar off
      - name: Linting
        run: |
          cd buildstockbatch
          # stop the build if there are Python syntax errors or undefined names
          flake8 buildstockbatch --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 buildstockbatch --count --statistics --exit-zero
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     limit-access-to-users: nmerket,asparke2
      - name: Run PyTest and Coverage
        run: |
          export OPENSTUDIO_EXE="$(pwd)/OpenStudio-3.6.1+bb9481519e-Ubuntu-20.04-x86_64/usr/local/openstudio-3.6.1/bin/openstudio"
          export OPENSTUDIO_COMSTOCK="$(pwd)/OpenStudio-3.4.0+4bd816f785-Ubuntu-20.04/usr/local/openstudio-3.4.0/bin/openstudio"
          cd buildstockbatch
          pytest --junitxml=coverage/junit.xml --cov=buildstockbatch --cov-report=xml:coverage/coverage.xml --cov-report=html:coverage/htmlreport -k "test_resstock_local_batch[national_baseline] or test_comstock_local_batch"
      - name: Save logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: gem-logs
          path: comstock/resources/.custom_gems/*.log
      - name: Save simulation output on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: comstock-test-output
          path: comstock/baseline_test_output
      - name: Test Report
        uses: mikepenz/action-junit-report@v3.5.2
        if: ${{ matrix.python-version == '3.11' }}
        with:
          report_paths: buildstockbatch/coverage/junit.xml
          check_name: Testing Report
          fail_on_failure: true
      - name: Save Coverage Report
        uses: actions/upload-artifact@v3
        if: ${{ matrix.python-version == '3.11' }}
        with:
          name: coverage-report-html
          path: buildstockbatch/coverage/htmlreport/
      - name: Report coverage to PR
        uses: 5monkeys/cobertura-action@v13
        if: ${{ matrix.python-version == '3.11' }}
        with:
          path: buildstockbatch/coverage/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 33
          fail_below_threshold: true
      - name: Build documentation
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          cd buildstockbatch/docs
          make html SPHINXOPTS="-W --keep-going -n"
      - name: Save Docs
        uses: actions/upload-artifact@v3
        if: ${{ matrix.python-version == '3.11' }}
        with:
          name: documentation
          path: buildstockbatch/docs/_build/html/
